name: Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Describe Your Feature
      description: Please describe your feature.
      placeholder: >
        A clear and concise description of what the problem is.
        (Help us understand the context and *why* for this feature, in addition to the *what*)
  - type: textarea
    attributes:
      label: Describe the Implementation Plan.
      placeholder: >
        A clear and concise description of what and how you want it to happen.
  - type: textarea